// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://example.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/animals": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ZooStat"
                ],
                "summary": "Получить всех животных по виду",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Animal"
                            }
                        }
                    }
                }
            }
        },
        "/api/animals": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animals"
                ],
                "summary": "Получить всех животных",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Animal"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animals"
                ],
                "summary": "Добавить животное",
                "parameters": [
                    {
                        "description": "Animal Data",
                        "name": "animal",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Animal"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Animal"
                        }
                    }
                }
            }
        },
        "/api/animals/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "animals"
                ],
                "summary": "Получить животное по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Animal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Animal"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "animals"
                ],
                "summary": "Удалить животное",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Animal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/schedules": {
            "get": {
                "description": "Get feeding schedule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feeding_schedule"
                ],
                "summary": "Get feeding schedule by ID",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.FeedingSchedule"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new feeding schedule for an animal with specified feeding time and food type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feeding_schedule"
                ],
                "summary": "Add a new feeding schedule",
                "parameters": [
                    {
                        "description": "Feeding schedule information",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AddScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete schedule by animalID and time from repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feeding_schedule"
                ],
                "summary": "Delete feeding schedule",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/zoostat/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ZooStat"
                ],
                "summary": "Получить все клетки",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Enclosure"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.AddScheduleRequest": {
            "type": "object",
            "properties": {
                "animalId": {
                    "type": "string"
                },
                "feedingTime": {
                    "type": "string"
                },
                "foodType": {
                    "type": "string"
                }
            }
        },
        "model.Animal": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "string"
                },
                "birthDate": {
                    "type": "string"
                },
                "enclosureID": {
                    "type": "string"
                },
                "favoriteFood": {
                    "$ref": "#/definitions/model.Food"
                },
                "gender": {
                    "$ref": "#/definitions/model.Gender"
                },
                "healthStatus": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "species": {
                    "$ref": "#/definitions/model.Species"
                }
            }
        },
        "model.Enclosure": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "string"
                },
                "animalsID": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "currentCount": {
                    "type": "integer"
                },
                "maxCapacity": {
                    "type": "integer"
                },
                "size": {
                    "$ref": "#/definitions/model.Size"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.FeedingSchedule": {
            "type": "object",
            "properties": {
                "animalID": {
                    "type": "string"
                },
                "feedingTime": {
                    "type": "string"
                },
                "foodType": {
                    "type": "string"
                }
            }
        },
        "model.Food": {
            "type": "object",
            "properties": {
                "foodType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.Gender": {
            "type": "string",
            "enum": [
                "male",
                "female"
            ],
            "x-enum-varnames": [
                "Male",
                "Female"
            ]
        },
        "model.Size": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "lenght": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "model.Species": {
            "type": "object",
            "properties": {
                "animalType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "My Chi API",
	Description:      "This is a sample server for my API using Chi",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
